# Generated by Django 5.1.2 on 2024-10-18 13:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_textvector_encrypted_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='apilog',
            name='processing_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='textvector',
            name='checksum',
            field=models.CharField(max_length=64, null=True),
        ),
        migrations.AlterField(
            model_name='apilog',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='textvector',
            name='encrypted_vector',
            field=models.BinaryField(),
        ),
    ]
